[2023-06-19 14:29:53,291] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: bash_script.run_bash_script manual__2023-06-19T14:29:50.249820+00:00 [queued]>
[2023-06-19 14:29:53,302] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: bash_script.run_bash_script manual__2023-06-19T14:29:50.249820+00:00 [queued]>
[2023-06-19 14:29:53,302] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 14:29:53,302] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-06-19 14:29:53,302] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 14:29:53,315] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): run_bash_script> on 2023-06-19 14:29:50.249820+00:00
[2023-06-19 14:29:53,319] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2023-06-19 14:29:53,322] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bash_script', 'run_bash_script', 'manual__2023-06-19T14:29:50.249820+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/run_crawl.py', '--cfg-path', '/tmp/tmprqxvgue3', '--error-file', '/tmp/tmpl7e6lny8']
[2023-06-19 14:29:53,322] {standard_task_runner.py:80} INFO - Job 3: Subtask run_bash_script
[2023-06-19 14:29:53,376] {task_command.py:371} INFO - Running <TaskInstance: bash_script.run_bash_script manual__2023-06-19T14:29:50.249820+00:00 [running]> on host 2ed9c3880c66
[2023-06-19 14:29:53,444] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bash_script
AIRFLOW_CTX_TASK_ID=run_bash_script
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T14:29:50.249820+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-19T14:29:50.249820+00:00
[2023-06-19 14:29:53,445] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-19 14:29:53,445] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd ../../crawler && scrapy crawl crawler2']
[2023-06-19 14:29:53,462] {subprocess.py:85} INFO - Output:
[2023-06-19 14:29:53,469] {subprocess.py:92} INFO - bash: line 1: cd: ../../crawler: No such file or directory
[2023-06-19 14:29:53,470] {subprocess.py:96} INFO - Command exited with return code 1
[2023-06-19 14:29:53,484] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-19 14:29:53,488] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=bash_script, task_id=run_bash_script, execution_date=20230619T142950, start_date=20230619T142953, end_date=20230619T142953
[2023-06-19 14:29:53,500] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task run_bash_script (Bash command failed. The command returned a non-zero exit code 1.; 149)
[2023-06-19 14:29:53,534] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-19 14:29:53,562] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
